name: Manual Release to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Attempt to Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: wheels
        pattern: wheels-*
        merge-multiple: true
      continue-on-error: true
    - name: Publish to PyPI
      uses: PyO3/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      with:
        command: upload
        args: --skip-existing wheels/*/*
      continue-on-error: true 